Repository cosmos/peggy, pull requests merged in 2019-12, with the labels that each got.

#100 Add Keeper to EthBridge module and use expected keepers abstraction
  CHANGELOG.md
  README.md
  app/app.go
  x/ethbridge/alias.go
  x/ethbridge/handler.go
  x/ethbridge/keeper/keeper.go
  x/ethbridge/module.go
  x/ethbridge/querier/querier.go
  x/ethbridge/test_common.go
  x/ethbridge/types/expected_keepers.go
  x/oracle/keeper/keeper.go
  x/oracle/types/expected_keepers.go
  x/oracle/types/prophecy.go
Labels: R4R

#104 Core demo tasks (usability updates, bug fixes, readme changes)
  README.md
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/txs/relayToCosmos.go
  docs/PeggyForRemix.sol
  docs/cosmos-to-ethereum.md
  docs/ethereum-to-cosmos.md
  docs/initialization.md
  docs/local-ethereum-usage.md
  docs/ropsten-testnet-usage.md
  testnet-contracts/contracts/CosmosBridge.sol
  testnet-contracts/scripts/sendLockTx.js
  x/ethbridge/client/rest/rest.go
  x/ethbridge/handler_test.go
  x/ethbridge/types/events.go
  x/ethbridge/types/msg_burn.go
  x/ethbridge/types/msg_lock.go
Labels: R4R, docs

#93 Add code coverage
  .circleci/config.yml
  .codecov.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: R4R, build
